version: '3.8'
services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 2XjE96zCPscH
      POSTGRES_DB: team_challenge
    volumes:
      - db-data:/var/lib/postgresql/data

volumes:
  db-data: