version: '3'
services:
  db:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 212314fXjE96zCPscH
      MYSQL_DATABASE: team_challenge
      MYSQL_USER: master
      MYSQL_PASSWORD: 21231x2314fXjdE96zCPscH
    volumes:
      - ./data:/var/lib/mysql
    ports:
      - 3307:3306

  be:
    build:
      context: .
      dockerfile: Backend/Dockerfile
    ports:
      - 8000:80
    volumes:
      - .:/var/www/html
